allowBuilds:
  esbuild: true
  sharp: true
shellEmulator: true
trustPolicy: no-downgrade
patchedDependencies:
  '@qwik.dev/partytown@0.11.2': patches/@qwik.dev__partytown@0.11.2.patch
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
